{
  imports = [
    ./actualbudget.nix
    ./authentik.nix
    ./bentopdf.nix
    ./convertx.nix
    ./crowdsec.nix
    ./garage.nix
    ./immich.nix
    ./ip2location.nix
    ./livesync.nix
    ./nixflix.nix
    ./niks3.nix
    ./geoipupdate.nix
    ./psitransfer.nix
    ./postgresql.nix
    ./splitpro.nix
    ./storage-backups.nix
    ./traefik.nix
  ];
}
